### PR TITLE
Only send HEARTBEAT if connection has been idle

### PR DESCRIPTION
**Pull request by emontnemery**
Rewrite logic for sending HEARTBEAT such that it's only sent if connection has been idle.

### CODE REVIEW

**Comment by TradeFace** [comment]
@emontnemery can you update the version to 1.3.1 so I can release it to pypi after merge?

**Comment by emontnemery** [comment]
Sure, just in `config.py`, right?

**Comment by TradeFace** [comment]
yep just .config.py.

**Comment by emontnemery** [comment]
Damnit, this was meant for development branch, not for master "#"¤"#%#%
How about making development default branch for PRs? :)

**Comment by TradeFace** [comment]
I'll merge it back, np :+1: 
I've set the default branch to dev.

**Comment by jkerdreux-imt** [comment]
Hey hey .. not a single disconnect / reconnect since 12 minutes on the 
SHP6 :)

After 12 mins:

2020-06-03 22:19:50 i7 tuyaface.tuyaclient[43248] DEBUG (192.168.1.63) PING
2020-06-03 22:19:50 i7 tuyaface[43248] DEBUG (192.168.1.63) sending msg (seq 43): [9:HEART_BEAT] payload: [None]
2020-06-03 22:19:50 i7 tuyaface[43248] DEBUG (192.168.1.63) received msg (seq 0): [8:STATUS] rc: [0] payload: [{"devId":"142200252462ab419539","dps":{"6":2293},"t":1591215590}]
{'devId': '142200252462ab419539', 'dps': {'6': 2293}, 't': 1591215590} status
2020-06-03 22:19:50 i7 tuyaface.tuyaclient[43248] ERROR (192.168.1.63) exception when reading from socket
2020-06-03 22:19:50 i7 tuyaface.tuyaclient[43248] WARNING (192.168.1.63) reconnecting


I used to have a disconnect / reconnect every 2 minutes.

We still have collision on the ping, but it's way better ;)

**Comment by jkerdreux-imt** [comment]
Great news in !! :)


After my last email, I checked the reconnect.. and discovered that 
update status are 5 seconds
periodic.. but the heartbeat too :(

So if we receive a status, a collision will probably occurs. So I 
decided to with other heartbeat
rate. Here my current settings.

HEART_BEAT_TIME = 7
CONNECTION_STALE_TIME = 7
RECONNECT_COOL_DOWN_TIME = 7

I changed HB rate to 7 seconds (more than 5 sec), the same for STALE. 
With this settings,
I managed to have a full afternoon without any reconnect. Tested on both 
BW SHP6 / SHP7
and LSC Lamp.

This evening, I get one connection issue, but I was unable to reconnect 
quickly (even w/ the COOL_DOWN..)
I wondering if there is no a issue here. I need to wait something like 
15 loops before the connection was back.
In previous implementation (without HB), I managed to reconnect with 0.3 
sec after a connection reset,
I don't understand why I have issues with 5 secs.

Could you please test w/ the 7/7/7 combo ?

Thanks.

**Comment by emontnemery** [comment]
@jkerdreux-imt Thanks for reporting back, but it's a bit unclear.

>discovered that update status are 5 seconds periodic..

Why do you need to do 5 second periodic status updates if you use TuyaClient, you will get status updates pushed via the `on_status` callback?

> Could you please test w/ the 7/7/7 combo 

You can just override the constants yourself:
```py
tuyaclient.HEART_BEAT_TIME = 7
tuyaclient.CONNECTION_STALE_TIME= 7
tuyaclient.RECONNECT_COOL_DOWN_TIME= 7
```
Or do you think the 5s timeouts are too short?

> This evening, I get one connection issue, but I was unable to reconnect
quickly (even w/ the COOL_DOWN..)
I wondering if there is no a issue here. I need to wait something like
15 loops before the connection was back.

Can you share a log with loglevel set to DEBUG showint the disconnect+reconnect sequence please?

**Comment by jkerdreux-imt** [comment]
On 6/5/20 10:12 AM, Erik Montnemery wrote:
>
> @jkerdreux-imt <https://github.com/jkerdreux-imt> Thanks for reporting 
> back, but it's a bit unclear.
>
>     discovered that update status are 5 seconds periodic..
>
> Why do you need to do 5 second periodic status updates if you use 
> TuyaClient, you will get status updates pushed via the |on_status| 
> callback?
>
The devices itself have an internal refresh status of 5 seconds. I think 
this is the default in the tuya SDK. For example on SHP6, every 5 
seconds the device senses the current / voltage. If something changed, 
the device send a status update. On the other side TuyaClient now send 
an heartbeat 5 sec after a status update. So quickly we will have some 
collision.


>     Could you please test w/ the 7/7/7 combo
>
> You can just override the constants yourself:
>
> tuyaclient.HEART_BEAT_TIME  =  7
> tuyaclient.CONNECTION_STALE_TIME=  7
> tuyaclient.RECONNECT_COOL_DOWN_TIME=  7

Patching constant in code at import is usually a bad idea..


Bye.

**Comment by emontnemery** [comment]
> The devices itself have an internal refresh status of 5 seconds. I think
this is the default in the tuya SDK. For example on SHP6, every 5
seconds the device senses the current / voltage.

OK, clear, then the 5s heartbeat timeouts are too short. I'll change it!

Again, thanks for testing!

**Pull request merged**
