### PR TITLE
Improve reconnect

### LINKED ISSUE #48: tuyaface spins out of control
As discussed here https://github.com/TradeFace/tuyamqtt/pull/14

### PR DESCRIPTION
**Pull request by emontnemery**
Closes #48

### CODE REVIEW

**Comment by emontnemery** [comment]
@TradeFace I think this should prevent any busy reconnect loops, please help to test if you have a good way of provoking them

**Comment by TradeFace** [comment]
I'll do some testing tomorrow!

**Comment by TradeFace** [comment]
From a quick test.... Much calmer, looks promising; I think it's fixed :100: 

Will monitor for a bit tomorrow
```
2020-06-03 01:38:47,647 WARNING  (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) reconnecting
2020-06-03 01:38:49,647 WARNING  (tuyamqtt_bfab167947172eb193wwc7xxx) [tuyaface.tuyaclient] (192.168.1.20) No reply to status
2020-06-03 01:38:52,619 INFO     (Thread-19) [tuyaface] (192.168.1.20) Connecting to 192.168.1.20
2020-06-03 01:38:52,621 INFO     (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) connected
2020-06-03 01:38:52,630 WARNING  (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) reconnecting
2020-06-03 01:38:54,652 WARNING  (tuyamqtt_bfab167947172eb193wwc7xxx) [tuyaface.tuyaclient] (192.168.1.20) No reply to status
2020-06-03 01:38:56,653 WARNING  (tuyamqtt_bfab167947172eb193wwc7xxx) [tuyaface.tuyaclient] (192.168.1.20) No reply to status
2020-06-03 01:38:57,622 INFO     (Thread-19) [tuyaface] (192.168.1.20) Connecting to 192.168.1.20
2020-06-03 01:38:57,669 INFO     (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) connected
2020-06-03 01:38:57,679 WARNING  (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) reconnecting
2020-06-03 01:38:59,679 WARNING  (tuyamqtt_bfab167947172eb193wwc7xxx) [tuyaface.tuyaclient] (192.168.1.20) No reply to status
2020-06-03 01:39:02,624 INFO     (Thread-19) [tuyaface] (192.168.1.20) Connecting to 192.168.1.20
2020-06-03 01:39:02,628 INFO     (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) connected
2020-06-03 01:39:02,637 WARNING  (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) reconnecting
2020-06-03 01:39:04,684 WARNING  (tuyamqtt_bfab167947172eb193wwc7xxx) [tuyaface.tuyaclient] (192.168.1.20) No reply to status
2020-06-03 01:39:06,685 WARNING  (tuyamqtt_bfab167947172eb193wwc7xxx) [tuyaface.tuyaclient] (192.168.1.20) No reply to status
2020-06-03 01:39:07,629 INFO     (Thread-19) [tuyaface] (192.168.1.20) Connecting to 192.168.1.20
2020-06-03 01:39:07,703 INFO     (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) connected
2020-06-03 01:39:07,712 WARNING  (Thread-19) [tuyaface.tuyaclient] (192.168.1.20) reconnecting
```

**Comment by jkerdreux-imt** [comment]
This works way better on the shp6 (BW). I get a reconnect loop at 
startup on this device in most cases.
It looks fine now. I still have some reconnect if the device receive a 
ping just after a status update. I think
we should ping only if we have 5 seconds of inactivity, not just a pure 
periodic behavior.

**Comment by emontnemery** [comment]
> I still have some reconnect if the device receive a ping just after a status update.

Can this be reproduced, and you're sure the disconnect is due to the short time between messages? If you can confirm it I'll modify the ping logic as you propose.

**Comment by TradeFace** [comment]
I did some more monitoring today. As far as I can tell it is fixed. IMO we can release v1.3

**Pull request merged**
